### ISSUE TITLE
Animate the transition between workspaces

### ISSUE THREAD

**Issue by KieranCodes** [vaxerski/Hypr#22]
**Describe the solution you'd like**
Animate the transition between workspaces. Either a fade transition or a wiping would be great.

**Comment by vaxerski** [comment]
fade - impossible, thats down to your compositor
wipe - sure

**Comment by vaxerski** [comment]
I have added them, but since those types of animations aren't really the job of a window manager, they might be kinda slow and might work wonkily with compositors. 

It's not really the window manager's job.

I might or might not improve them in the future, depending on the demand and the actual doability.
